// Generated by dia2code
#ifndef STATE__ARCHER__H
#define STATE__ARCHER__H

#include <string>
#include <vector>

namespace state {
  class Personnage;
}

#include "Personnage.h"

namespace state {

  /// class Archer - 
  class Archer : public state::Personnage {
    // Attributes
  protected:
    std::string nomArme     = "Arc";
    int codeArme     = 1;
    // Operations
  public:
    std::vector<Position> getLegalMove ();
    std::vector<Position> getLegalAttack ();
    // Setters and Getters
  };

};

#endif
