// Generated by dia2code
#ifndef STATE__ARCHER__H
#define STATE__ARCHER__H


namespace state {
  class Personnage;
}

#include "Personnage.h"

namespace state {

  /// class Archer - 
  class Archer : public state::Personnage {
    // Operations
  public:
    Archer ();
    // Setters and Getters
  };

};

#endif
