// Generated by dia2code
#ifndef STATE__BRIGAND__H
#define STATE__BRIGAND__H


namespace state {
  class Personnage;
}

#include "Personnage.h"

namespace state {

  /// class Brigand - 
  class Brigand : public state::Personnage {
    // Operations
  public:
    Brigand ();
    // Setters and Getters
  };

};

#endif
