// Generated by dia2code
#ifndef STATE__BRIGAND__H
#define STATE__BRIGAND__H

#include <string>
#include <vector>

namespace state {
  class Personnage;
}

#include "Personnage.h"

namespace state {

  /// class Brigand - 
  class Brigand : public state::Personnage {
    // Attributes
  protected:
    std::string nomArme     = "Hache";
    int codeArme     = 2;
    // Operations
  public:
    std::vector<Position> getLegalMove ();
    std::vector<Position> getLegalAttack ();
    // Setters and Getters
  };

};

#endif
