// Generated by dia2code
#ifndef STATE__CHEVALIER__H
#define STATE__CHEVALIER__H

#include <string>
#include <vector>

namespace state {
  class Personnage;
}

#include "Personnage.h"

namespace state {

  /// class Chevalier - 
  class Chevalier : public state::Personnage {
    // Attributes
  protected:
    std::string nomArme     = "Lance";
    int codeArme     = 3;
    // Operations
  public:
    std::vector<Position> getLegalMove ();
    std::vector<Position> getLegalAttack ();
    // Setters and Getters
  };

};

#endif
