// Generated by dia2code
#ifndef STATE__CHEVALIER__H
#define STATE__CHEVALIER__H


namespace state {
  class Personnage;
}

#include "Personnage.h"

namespace state {

  /// class Chevalier - 
  class Chevalier : public state::Personnage {
    // Operations
  public:
    Chevalier ();
    // Setters and Getters
  };

};

#endif
