// Generated by dia2code
#ifndef STATE__CORRESPONDANCES__H
#define STATE__CORRESPONDANCES__H

#include <map>

#include "TypePersonnageID.h"
#include "TerrainNonPraticableID.h"
#include "TerrainPraticableID.h"

namespace state {

  /// class Correspondances - 
  class Correspondances {
    // Associations
    // Attributes
  private:
    std::map<int, TypePersonnageID> correspondances_personnage;
    std::map<int, TerrainPraticableID> correspondances_TP;
    std::map<int, TerrainNonPraticableID> correspondances_TNP;
    // Operations
  public:
    Correspondances ();
    std::map<int, TerrainPraticableID>& getCorrespondanceTP ();
    std::map<int, TerrainNonPraticableID>& getCorrespondanceTNP ();
    std::map<int, TypePersonnageID>& getCorrespondancePersonnage ();
    // Setters and Getters
  };

};

#endif
