// Generated by dia2code
#ifndef STATE__ELEMENT__H
#define STATE__ELEMENT__H

#include <string>

namespace state {
  class Position;
  class Statistiques;
  class Element;
  class Correspondances;
}

#include "Position.h"
#include "Statistiques.h"
#include "Correspondances.h"

namespace state {

  /// class Element - 
  class Element {
    // Associations
    // Attributes
  protected:
    std::string nom;
    Position position;
    Statistiques statistiques;
    int codeTuile;
    // Operations
  public:
    Element ();
    virtual bool isTerrain () = 0;
    std::string getNom ();
    Position& getPosition ();
    Statistiques& getStatistiques ();
    virtual bool equals (Element& other);
    int getCodeTuile ();
    void setCodeTuile (int newCodeTuile);
    virtual ~Element ();
    // Setters and Getters
  };

};

#endif
