// Generated by dia2code
#ifndef STATE__ETAT__H
#define STATE__ETAT__H

#include <vector>
#include <memory>
#include <string>

namespace state {
  class Correspondances;
  class Terrain;
  class Personnage;
}

#include "Terrain.h"
#include "Personnage.h"

namespace state {

  /// class Etat - 
  class Etat {
    // Associations
    // Attributes
  private:
    std::vector<std::vector<std::unique_ptr<Terrain>>> grille;
    std::vector<std::unique_ptr<Personnage>> personnages;
    int tour;
    bool fin;
    // Operations
  public:
    std::vector<std::vector<std::unique_ptr<Terrain>>>& getGrille ();
    std::vector<std::unique_ptr<Personnage>>& getPersonnages ();
    int getTour ();
    int initGrille (std::string chemin_map_txt, unsigned int longueur, unsigned int largeur, Correspondances& correspondances);
    int initPersonnages (Correspondances& correspondances);
    // Setters and Getters
  };

};

#endif
