// Generated by dia2code
#ifndef STATE__GUERRIER__H
#define STATE__GUERRIER__H

#include <string>
#include <vector>

namespace state {
  class Personnage;
}

#include "Personnage.h"

namespace state {

  /// class Guerrier - 
  class Guerrier : public state::Personnage {
    // Attributes
  public:
    std::string nomArme     = "Epee";
  protected:
    int codeArme     = 4;
    // Operations
  public:
    std::vector<Position> getLegalMove ();
    std::vector<Position> getLegalAttack ();
    // Setters and Getters
  };

};

#endif
