// Generated by dia2code
#ifndef STATE__GUERRIER__H
#define STATE__GUERRIER__H


namespace state {
  class Personnage;
}

#include "Personnage.h"

namespace state {

  /// class Guerrier - 
  class Guerrier : public state::Personnage {
    // Operations
  public:
    Guerrier ();
    // Setters and Getters
  };

};

#endif
