// Generated by dia2code
#ifndef STATE__PERSONNAGE__H
#define STATE__PERSONNAGE__H

#include <string>
#include <vector>

namespace state {
  class Element;
}

#include "StatutPersonnageID.h"
#include "Element.h"

namespace state {

  /// class Personnage - 
  class Personnage : public state::Element {
    // Associations
    // Attributes
  protected:
    bool camp;
    std::string nomArme;
    int codeArme;
    StatutPersonnageID statut;
    // Operations
  public:
    bool isTerrain ();
    bool getCamp ();
    std::string getNomArme ();
    StatutPersonnageID getStatut ();
    void setStatut (StatutPersonnageID newStatut);
    virtual std::vector<Position> getLegalMove ();
    virtual std::vector<Position> getLegalAttack ();
    // Setters and Getters
  };

};

#endif
