// Generated by dia2code
#ifndef STATE__STATEEVENTID__H
#define STATE__STATEEVENTID__H


namespace state {

  enum StateEventID {
    ALLCHANGED,
    GRILLECHANGED,
    TOURCHANGED,
    PERSONNAGECHANGED,
    TEXTECHANGED
  };

};

#endif
