// Generated by dia2code
#ifndef STATE__STATEEVENT__H
#define STATE__STATEEVENT__H

#include <string>

#include "StateEventID.h"

namespace state {

  /// class StateEvent - 
  class StateEvent {
    // Associations
    // Attributes
  public:
    StateEventID stateEventID;
    std::string texte;
    std::string texteInfos;
    std::string texteStats;
    bool camp;
    // Operations
  public:
    StateEvent (StateEventID se);
    void setStateEventID (StateEventID newID);
    // Setters and Getters
  };

};

#endif
