// Generated by dia2code
#ifndef STATE__STATISTIQUES__H
#define STATE__STATISTIQUES__H


namespace state {

  /// class Statistiques - 
  class Statistiques {
    // Attributes
  private:
    int pv;
    int attaque;
    int defense;
    int esquive;
    int critique;
    // Operations
  public:
    int getPV ();
    int getAttaque ();
    int getDefense ();
    int getEsquive ();
    int getCritique ();
    void setPV (int newPV);
    void setAttaque (int newAttaque);
    void setDefense (int newDefense);
    void setEsquive (int newEsquive);
    void setCritique (int newCritique);
    // Setters and Getters
  };

};

#endif
