// Generated by dia2code
#ifndef STATE__STATUTPERSONNAGEID__H
#define STATE__STATUTPERSONNAGEID__H


namespace state {

  enum StatutPersonnageID {
    SELECTIONNE     = 1,
    DISPONIBLE     = 2,
    ATTENTE     = 3,
    MORT     = 4
  };

};

#endif
