// Generated by dia2code
#ifndef STATE__TERRAIN__H
#define STATE__TERRAIN__H


namespace state {
  class Etat;
  class Element;
}

#include "Element.h"

namespace state {

  /// class Terrain - 
  class Terrain : public state::Element {
    // Operations
  public:
    Terrain ();
    bool isTerrain ();
    virtual bool isPraticable () = 0;
    bool isOccupe (Etat& etat);
    // Setters and Getters
  };

};

#endif
