// Generated by dia2code
#ifndef STATE__TERRAINPRATICABLE__H
#define STATE__TERRAINPRATICABLE__H


namespace state {
  class Element;
  class Terrain;
}

#include "TerrainPraticableID.h"
#include "Terrain.h"

namespace state {

  /// class TerrainPraticable - 
  class TerrainPraticable : public state::Terrain {
    // Associations
    // Attributes
  protected:
    TerrainPraticableID typeID;
    // Operations
  public:
    TerrainPraticable (TerrainPraticableID id, int newX, int newY, int newCodeTuile);
    bool isPraticable ();
    TerrainPraticableID getTerrainPraticableID ();
    bool equals (Element& other);
    // Setters and Getters
  };

};

#endif
