// Generated by dia2code
#ifndef STATE__TERRAINNONPRATICABLEID__H
#define STATE__TERRAINNONPRATICABLEID__H


namespace state {

  enum TerrainNonPraticableID {
    MUR     = 1,
    RIVIERE     = 2,
    MONTAGNE     = 3,
    FALAISE     = 4
  };

};

#endif
