// Generated by dia2code
#ifndef STATE__TERRAINPRATICABLEID__H
#define STATE__TERRAINPRATICABLEID__H


namespace state {

  enum TerrainPraticableID {
    PLAINE     = 1,
    FORET     = 2,
    COLLINE     = 3,
    PONT     = 4,
    FORTERESSE     = 5,
    MAISON     = 6
  };

};

#endif
