// Generated by dia2code
#ifndef STATE__TYPEPERSONNAGEID__H
#define STATE__TYPEPERSONNAGEID__H


namespace state {

  enum TypePersonnageID {
    ARCHER     = 1,
    BRIGAND     = 2,
    CHEVALIER     = 3,
    GUERRIER     = 4
  };

};

#endif
