// Generated by dia2code
#ifndef RENDER__CURSEUREVENTID__H
#define RENDER__CURSEUREVENTID__H


namespace render {

  enum CurseurEventID {
    A     = 1,
    Z     = 2,
    M     = 3,
    UPDATE     = 4,
    R     = 5
  };

};

#endif
