// Generated by dia2code
#ifndef RENDER__CURSEUREVENT__H
#define RENDER__CURSEUREVENT__H


#include "CurseurEventID.h"

namespace render {

  /// class CurseurEvent - 
  class CurseurEvent {
    // Associations
    // Attributes
  public:
    CurseurEventID touche;
    // Operations
  public:
    CurseurEvent (CurseurEventID touche);
    // Setters and Getters
  };

};

#endif
