// Generated by dia2code
#ifndef RENDER__ETATTILESET__H
#define RENDER__ETATTILESET__H

#include <vector>
#include <string>

namespace render {
  class Tile;
  class TileSet;
}

#include "Tile.h"
#include "TileSet.h"

namespace render {

  /// class EtatTileSet - 
  class EtatTileSet : public render::TileSet {
    // Attributes
  private:
    std::vector<Tile> chars;
    // Operations
  public:
    EtatTileSet ();
    const std::string  getImageFile ();
    const Tile&  getCharTile (char c);
    // Setters and Getters
  };

};

#endif
