// Generated by dia2code
#ifndef RENDER__GRILLETILESET__H
#define RENDER__GRILLETILESET__H

#include <vector>
#include <string>

namespace render {
  class Tile;
};
namespace state {
  class Element;
};
namespace render {
  class TileSet;
}

#include "Tile.h"
#include "TileSet.h"

namespace render {

  /// class GrilleTileSet - 
  class GrilleTileSet : public render::TileSet {
    // Attributes
  private:
    std::vector<Tile> terrainsPraticables;
     std::vector<Tile> terrainsNonPraticables;
    // Operations
  public:
    GrilleTileSet ();
    const std::string  getImageFile ();
    const Tile&  getTile (state::Element& e);
    // Setters and Getters
  };

};

#endif
