// Generated by dia2code
#ifndef RENDER__LAYER__H
#define RENDER__LAYER__H


namespace render {
  class Surface;
  class TileSet;
}

#include "TileSet.h"

namespace render {

  /// class Layer - 
  class Layer {
    // Associations
    // Attributes
  protected:
    Surface* surface;
    TileSet* tileset;
    // Operations
  public:
    Layer ();
    virtual ~Layer ();
    Surface* getSurface ();
    void setSurface (Surface* surface);
    // Setters and Getters
  };

};

#endif
