// Generated by dia2code
#ifndef RENDER__LAYER__H
#define RENDER__LAYER__H

#include <memory>

namespace render {
  class MyEntity;
}

#include "MyEntity.h"

namespace render {

  /// class Layer - 
  class Layer {
    // Associations
    // Attributes
  public:
    std::unique_ptr<MyEntity> ptr_entity;
    // Operations
  public:
    Layer ();
    ~Layer ();
    std::unique_ptr<MyEntity> getPtrEntity ();
    // Setters and Getters
  };

};

#endif
