// Generated by dia2code
#ifndef RENDER__MYENTITY__H
#define RENDER__MYENTITY__H

#include <SFML/Graphics.hpp>
#include <string>

namespace sf {
  class VertexArray;
  class Texture;
  class Drawable;
  class Transformable;
}


namespace render {

  /// class MyEntity - 
  class MyEntity : public sf::Drawable, public sf::Transformable {
    // Attributes
  public:
    sf::VertexArray quads;
    sf::Texture texture;
    // Operations
  public:
    virtual void draw (sf::RenderTarget& target, sf::RenderStates states) const;
    bool load (const std::string & image, sf::Vector2u tileSize,  const int*  tiles, unsigned int width, unsigned int height);
    sf::Texture getTexture ();
    // Setters and Getters
  };

};

#endif
