// Generated by dia2code
#ifndef RENDER__PERSONNAGETILESET__H
#define RENDER__PERSONNAGETILESET__H

#include <vector>
#include <string>

namespace render {
  class Tile;
};
namespace state {
  class Element;
};
namespace render {
  class TileSet;
}

#include "Tile.h"
#include "TileSet.h"

namespace render {

  /// class PersonnageTileSet - 
  class PersonnageTileSet : public render::TileSet {
    // Attributes
  public:
    std::vector<Tile> personnage;
    // Operations
  public:
    PersonnageTileSet ();
    const std::string  getImageFile ();
    const Tile&  getTile (state::Element& e);
    // Setters and Getters
  };

};

#endif
