// Generated by dia2code
#ifndef RENDER__SCENE__H
#define RENDER__SCENE__H

#include <stdlib.h>
#include <SFML/Graphics.hpp>

namespace state {
  class Etat;
};
namespace render {
  class StateLayer;
};
namespace sf {
  class RenderWindow;
};
namespace state {
  class IObserver;
}

#include "StateLayer.h"
#include "state/IObserver.h"
#include "state/Etat.h"

namespace render {

  /// class Scene - 
  class Scene : public state::IObserver {
    // Associations
    // Attributes
  private:
    state::Etat& etat;
    size_t width;
    size_t height;
    StateLayer stateLayer;
    // Operations
  public:
    Scene (state::Etat& etat);
    size_t getWidth ();
    size_t getHeight ();
    void stateChanged (const state::StateEvent& e, state::Etat& etat);
    void draw (sf::RenderWindow& window);
    StateLayer& getStateLayer ();
    // Setters and Getters
  };

};

#endif
