// Generated by dia2code
#ifndef RENDER__TILE__H
#define RENDER__TILE__H


namespace render {

  /// class Tile - 
  class Tile {
    // Attributes
  protected:
    int x;
    int y;
    int hauteur     = 16;
    int largeur     = 16;
    // Operations
  public:
    Tile ();
    const int getX ();
    const int getY ();
    // Setters and Getters
  };

};

#endif
