// Generated by dia2code
#ifndef RENDER__TILESETID__H
#define RENDER__TILESETID__H


namespace render {

  enum TileSetID {
    INFOSTILESET     = 1,
    PERSONNAGETILESET     = 2,
    GRILLETILESET     = 3,
    CURSEURTILESET     = 4
  };

};

#endif
