// Generated by dia2code
#ifndef RENDER__TILESET__H
#define RENDER__TILESET__H

#include <string>
#include <SFML/Graphics.hpp>

namespace sf {
  class Texture;
}

#include "TileSetID.h"

namespace render {

  /// class TileSet - 
  class TileSet {
    // Associations
    // Attributes
  private:
    TileSetID id;
    int cellWidth;
    int cellHeight;
    std::string imageFile;
    sf::Texture textureTileset;
    // Operations
  public:
    TileSet (TileSetID newID);
    const std::string  getImageFile ();
    int const getCellWidth ();
    int const getCellHeight ();
    int const getTileSetID ();
    sf::Texture& getTexture ();
    // Setters and Getters
  };

};

#endif
