// Generated by dia2code
#ifndef AI__DEEPIA__H
#define AI__DEEPIA__H

#include <SFML/Graphics.hpp>
#include <vector>

namespace engine {
  class Moteur;
};
namespace sf {
  class RenderWindow;
};
namespace state {
  class Etat;
};
namespace ai {
  class IA;
};
namespace engine {
  class Action;
}

#include "IA.h"
#include "engine/Action.h"

namespace ai {

  /// class DeepIA - 
  class DeepIA : public ai::IA {
    // Attributes
  public:
    int profondeur     = 2;
    bool campChoisi;
    // Operations
  public:
    void run (engine::Moteur& moteur, sf::RenderWindow& window);
    int max (engine::Moteur& moteur, int profondeur);
    int min (engine::Moteur& moteur, int profondeur);
    int fonctionEvaluation (engine::Moteur& moteur);
    std::vector<engine::Action*> findActionsPossibles (state::Etat& etat, bool campChoisi);
    // Setters and Getters
  };

};

#endif
