// Generated by dia2code
#ifndef AI__DEEPIA__H
#define AI__DEEPIA__H

#include <SFML/Graphics.hpp>
#include <vector>

namespace engine {
  class Moteur;
};
namespace sf {
  class RenderWindow;
};
namespace state {
  class Etat;
};
namespace ai {
  class IA;
};
namespace engine {
  class Commande;
}

#include "IA.h"
#include "engine/Moteur.h"
#include "engine/Commande.h"

namespace ai {

  /// class DeepIA - 
  class DeepIA : public ai::IA, public engine::Moteur, public engine::Commande {
    // Operations
  public:
    void run (engine::Moteur& moteur, sf::RenderWindow& window);
    int max (engine::Moteur& moteur, int profondeur);
    int min (engine::Moteur& moteur, int profondeur);
    int fonctionEvaluation (state::Etat& etat);
    std::vector<engine::Commande&> findActionsPossibles (state::Etat& etat);
    // Setters and Getters
  };

};

#endif
