// Generated by dia2code
#ifndef AI__HEURISTICIA__H
#define AI__HEURISTICIA__H

#include <SFML/Graphics.hpp>
#include <vector>

namespace engine {
  class Moteur;
};
namespace sf {
  class RenderWindow;
};
namespace ai {
  class IA;
}

#include "IA.h"

namespace ai {

  /// class HeuristicIA - 
  class HeuristicIA : public ai::IA {
    // Operations
  public:
    void run (engine::Moteur& moteur, sf::RenderWindow& window);
    int findIndiceVoisin (engine::Moteur& moteur, int personnage);
    int findchoixOptimalDep (engine::Moteur&  moteur, int indiceVoisin, int personnage);
    int indiceMinimum (std::vector<int> liste);
    int indiceMaximum (std::vector<int> liste);
    state::Position findRefuge (engine::Moteur& moteur, int personnage);
    // Setters and Getters
  };

};

#endif
