// Generated by dia2code
#ifndef AI__RANDOMIA__H
#define AI__RANDOMIA__H


namespace engine {
  class Moteur;
};
namespace ai {
  class IA;
}

#include "IA.h"

namespace ai {

  /// class RandomIA - 
  class RandomIA : public ai::IA {
    // Operations
  public:
    void run (engine::Moteur& moteur);
    // Setters and Getters
  };

};

#endif
