// Generated by dia2code
#ifndef AI__SOMMET__H
#define AI__SOMMET__H

#include <vector>

namespace ai {
  class Sommet;
};
namespace state {
  class Etat;
}

namespace ai {

  /// class Sommet - 
  class Sommet {
    // Attributes
  private:
    state::Position position;
    int distanceSource;
    int distanceDestination;
    Sommet* predecesseur;
    Sommet* suivant;
    // Operations
  public:
    Sommet (state::Position newPosition);
    Sommet* getPredecesseur ();
    void setPredecesseur (Sommet* newPredecesseur);
    int getDistanceSource ();
    void setDistanceSource (int newDistanceSource);
    int getDistanceDestination ();
    void setDistanceDestination (int newDistanceDestination);
    state::Position getPosition ();
    void setPosition (state::Position newPosition);
    std::vector<Sommet> getVoisins (state::Etat& etat);
    int getCoutTotal ();
    // Setters and Getters
  };

};

#endif
