// Generated by dia2code
#ifndef AI__SOMMET__H
#define AI__SOMMET__H

#include <vector>

namespace state {
  class Position;
};
namespace ai {
  class Sommet;
};
namespace state {
  class Etat;
}

#include "state/Position.h"

namespace ai {

  /// class Sommet - 
  class Sommet {
    // Attributes
  private:
    state::Position position;
    int distanceSource;
    int distanceDestination;
    Sommet* predecesseur;
    // Operations
  public:
    Sommet (Sommet* predecesseur);
    Sommet* getPredecesseur ();
    void setPredecesseur (Sommet* newPredecesseur);
    int getDistanceSource ();
    void setDistanceSource (int newDistanceSource);
    int getDistanceDestination ();
    void setDistanceDestination (int newDistanceDestination);
    state::Position& getPosition ();
    void setPosition (state::Position newPosition);
    std::vector<Sommet> getVoisins (state::Etat& etat);
    int getCoutTotal ();
    ~Sommet ();
    const Sommet* getPredecesseurC ();
    void setPredecesseurC (const Sommet* newPredecesseur);
    Sommet ();
    // Setters and Getters
  };

};

#endif
