// Generated by dia2code
#ifndef ENGINE__ACTIONID__H
#define ENGINE__ACTIONID__H


namespace engine {

  enum ActionID {
    DEP_ACTION     = 1,
    ATTAQUE_ACTION     = 2,
    FINACTIONS_ACTION     = 3
  };

};

#endif
