// Generated by dia2code
#ifndef ENGINE__ACTION__H
#define ENGINE__ACTION__H


namespace state {
  class Etat;
}

#include "ActionID.h"

namespace engine {

  /// class Action - 
  class Action {
    // Attributes
  public:
    bool joueur;
  protected:
    ActionID id;
    // Operations
  public:
    virtual void apply (state::Etat& etat) = 0;
    virtual void undo (state::Etat& etat) = 0;
    ActionID getActionID ();
    bool getJoueur ();
    // Setters and Getters
  };

};

#endif
