// Generated by dia2code
#ifndef ENGINE__ACTION__H
#define ENGINE__ACTION__H


namespace state {
  class Etat;
}

namespace engine {

  /// class Action - 
  class Action {
    // Attributes
  public:
    bool joueur;
    // Operations
  public:
    virtual void apply (state::Etat& etat) = 0;
    virtual void undo (state::Etat& etat) = 0;
    // Setters and Getters
  };

};

#endif
