// Generated by dia2code
#ifndef ENGINE__ATTAQUE__H
#define ENGINE__ATTAQUE__H


namespace state {
  class Etat;
};
namespace engine {
  class Commande;
}

#include "CommandeID.h"
#include "Commande.h"

namespace engine {

  /// class Attaque - 
  class Attaque : public engine::Commande {
    // Attributes
  private:
    state::Personnage& attaquant;
    state::Personnage& cible;
    // Operations
  public:
    Attaque (state::Personnage& attaquant, state::Personnage& cible);
    CommandeID getCommandeID ();
    void execute (state::Etat& etat);
    // Setters and Getters
  };

};

#endif
