// Generated by dia2code
#ifndef ENGINE__COMMANDE__H
#define ENGINE__COMMANDE__H

#include <json/json.h>

namespace state {
  class Etat;
}

#include "CommandeID.h"
#include "state/Etat.h"

namespace engine {

  /// class Commande - 
  class Commande {
    // Attributes
  public:
    CommandeID id;
    bool joueur;
    // Operations
  public:
    CommandeID getCommandeID ();
    virtual void execute (state::Etat& etat) = 0;
    virtual Json::Value serialize () = 0;
    // Setters and Getters
  };

};

#endif
