// Generated by dia2code
#ifndef ENGINE__COMMANDE__H
#define ENGINE__COMMANDE__H


namespace state {
  class Etat;
}

#include "CommandeID.h"
#include "state/Etat.h"

namespace engine {

  /// class Commande - 
  class Commande {
    // Operations
  public:
    virtual CommandeID getCommandeID () = 0;
    virtual void execute (state::Etat& etat) = 0;
    // Setters and Getters
  };

};

#endif
