// Generated by dia2code
#ifndef ENGINE__COMMANDEID__H
#define ENGINE__COMMANDEID__H


namespace engine {

  enum CommandeID {
    DEPLACEMENT     = 1,
    ATTAQUE     = 2,
    FINACTIONS     = 3
  };

};

#endif
