// Generated by dia2code
#ifndef ENGINE__DEPLACEMENT__H
#define ENGINE__DEPLACEMENT__H

#include <json/json.h>

namespace state {
  class Etat;
};
namespace engine {
  class Commande;
}

#include "Commande.h"

namespace engine {

  /// class Deplacement - 
  class Deplacement : public engine::Commande {
    // Attributes
  private:
    state::Personnage& cible;
    state::Position& destination;
    // Operations
  public:
    Deplacement (state::Personnage& cible, state::Position& destination, bool joueur);
    void execute (state::Etat& etat);
    Json::Value serialize ();
    // Setters and Getters
  };

};

#endif
