// Generated by dia2code
#ifndef ENGINE__FINACTIONS__H
#define ENGINE__FINACTIONS__H

#include <json/json.h>

namespace state {
  class Etat;
};
namespace engine {
  class Commande;
}

#include "Commande.h"

namespace engine {

  /// class FinActions - 
  class FinActions : public engine::Commande {
    // Attributes
  private:
    state::Personnage& cible;
    // Operations
  public:
    FinActions (state::Personnage& cible, bool joueur);
    void execute (state::Etat& etat);
    Json::Value serialize ();
    // Setters and Getters
  };

};

#endif
