// Generated by dia2code
#ifndef ENGINE__MOTEUR__H
#define ENGINE__MOTEUR__H

#include <map>
#include <memory>
#include <vector>
#include <SFML/Graphics.hpp>

namespace state {
  class Etat;
};
namespace engine {
  class Action;
  class Commande;
};
namespace sf {
  class RenderWindow;
}

#include "state/Etat.h"
#include "Commande.h"
#include "Action.h"

namespace engine {

  /// class Moteur - 
  class Moteur {
    // Associations
    // Attributes
  private:
    state::Etat etatActuel;
    std::map<int, std::unique_ptr<Commande>> commandesActuelles;
    bool changementTour;
    bool joueurActif;
    std::vector<Action*> listeActionsJouees;
    // Operations
  public:
    Moteur ();
    ~Moteur ();
    state::Etat& getEtat ();
    void addCommande (int priorite, std::unique_ptr<Commande> ptr_cmd);
    void update (sf::RenderWindow& window);
    bool verificationFinDeTour ();
    void verificationDebutDeTour ();
    bool getJoueurActif ();
    void gestionCurseur (sf::Event newEvent, sf::RenderWindow& window, unsigned int largeur_map_cases, unsigned int longueur_map_cases);
    void updateAction (sf::RenderWindow&  window, Action* action);
    void undo (sf::RenderWindow& window, Action* action);
    void gestionCurseurRollback (sf::Event newEvent, sf::RenderWindow& window, unsigned int largeur_map_cases, unsigned int longueur_map_cases);
    void addAction (Action* newAction);
    // Setters and Getters
  };

};

#endif
