// Generated by dia2code
#ifndef SERVER__COMMANDSERVICE__H
#define SERVER__COMMANDSERVICE__H

#include <json/json.h>

namespace engine {
  class Moteur;
};
namespace server {
  class AbstractService;
}

#include "HttpStatus.h"
#include "AbstractService.h"
#include "engine/Moteur.h"

namespace server {

  /// class CommandService - 
  class CommandService : public server::AbstractService {
    // Associations
    // Attributes
  private:
    engine::Moteur& moteur;
    Json::Value listeCommand;
    // Operations
  public:
    CommandService (engine::Moteur& moteur);
    HttpStatus  get (Json::Value& out, int id) const;
    HttpStatus put (Json::Value& out, const Json::Value& in);
    bool isVersion ();
    // Setters and Getters
  };

};

#endif
