// Generated by dia2code
#ifndef CLIENT__CLIENT__H
#define CLIENT__CLIENT__H

#include <memory>
#include <mutex>

namespace Engine {
  class Observer;
};
namespace render {
  class Scene;
};
namespace Engine {
  class Moteur;
};
namespace ai {
  class AI;
}

#include "Engine/Observer.h"
#include "render/Scene.h"
#include "Engine/Moteur.h"
#include "ai/AI.h"

namespace client {

  /// class Client - 
  class Client : public Engine::Observer {
    // Associations
    // Attributes
  private:
    engine::Moteur& moteur;
    std::unique_ptr<ai::IA> armeeBleu;
    std::unique_ptr<ai::IA> armeeRouge;
    mutable std::mutex draw_mutex;
    // Operations
  public:
    Client ();
    void engineUpdated ();
    void engineUpdating ();
    void run ();
    // Setters and Getters
  };

};

#endif
