// Generated by dia2code
#ifndef CLIENT__NETWORKCLIENT__H
#define CLIENT__NETWORKCLIENT__H

#include <string>
#include <SFML/Graphics.hpp>
#include <json/json.h>

namespace engine {
  class Moteur;
};
namespace ai {
  class IA;
};
namespace sf {
  class RenderWindow;
};
namespace engine {
  class Observer;
};
namespace render {
  class StateLayer;
}

#include "engine/Moteur.h"
#include "engine/Observer.h"
#include "render/StateLayer.h"
#include "ai/IA.h"

namespace client {

  /// class NetworkClient - 
  class NetworkClient : public engine::Observer {
    // Associations
    // Attributes
  private:
    std::string url;
    int port;
    int character;
    engine::Moteur moteur;
    ai::IA* player_ai;
    bool demarrage;
    sf::RenderWindow& window;
    // Operations
  public:
    NetworkClient (std::string& url, int port, int character, sf::RenderWindow& window);
    void engineUpdating ();
    void run ();
    void engineUpdated ();
  protected:
    std::string getGameStatus ();
    bool getServerCommands (Json::Value& out);
    void putServerCommand (engine::Commande* commande);
    // Setters and Getters
  };

};

#endif
